apiVersion: v1
kind: Service
metadata:
  name: cheapest-hotel-bot
  labels:
    app: cheapest-hotel-bot
spec:
  selector:
    app: cheapest-hotel-bot
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: ClusterIP
